// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCieWmB3z7zbzRQxMV7NrzqMpyFlYF2tP8',
    appId: '1:443323693631:web:34a300f2378078b3dc168a',
    messagingSenderId: '443323693631',
    projectId: 'android-push-notfication',
    authDomain: 'android-push-notfication.firebaseapp.com',
    storageBucket: 'android-push-notfication.firebasestorage.app',
    measurementId: 'G-BN4CWTX53Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm1hJ-WfRe7h60lMFzQrdSMW612VYMqWE',
    appId: '1:577563026053:android:42f58751081c9b3e8e7fec',
    messagingSenderId: '577563026053',
    projectId: 'eattendance-7c3f4',
    storageBucket: 'eattendance-7c3f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3h3HbSewHQdlkZR1pUoO-K4zCD6O6coM',
    appId: '1:443323693631:ios:83c1ee24a3c04276dc168a',
    messagingSenderId: '443323693631',
    projectId: 'android-push-notfication',
    storageBucket: 'android-push-notfication.firebasestorage.app',
    iosBundleId: 'com.example.eAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3h3HbSewHQdlkZR1pUoO-K4zCD6O6coM',
    appId: '1:443323693631:ios:83c1ee24a3c04276dc168a',
    messagingSenderId: '443323693631',
    projectId: 'android-push-notfication',
    storageBucket: 'android-push-notfication.firebasestorage.app',
    iosBundleId: 'com.example.eAttendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCieWmB3z7zbzRQxMV7NrzqMpyFlYF2tP8',
    appId: '1:443323693631:web:5df307bd7919072edc168a',
    messagingSenderId: '443323693631',
    projectId: 'android-push-notfication',
    authDomain: 'android-push-notfication.firebaseapp.com',
    storageBucket: 'android-push-notfication.firebasestorage.app',
    measurementId: 'G-YPYRNNECJX',
  );
}